### PR TITLE
Add several test related things

### PR DESCRIPTION
**Pull request by lrascao**
linting, coverage, eunit tests, common tests
Also, do away with the custom tree calculation of the eager push list, use whatever the peer service gives us

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Can you explain the change regarding the eager push list?

**Comment by lrascao** [comment]
Sure, when i added the tests, specifically the connectedness check, i found that some times (not all) plumtree would not have a fully connected graph (considering both eager and lazy lists), this happened more often on 4-node clusters. I'm thinking this is a remnant of the basho fork (that was manually building the spanning tree) and does not make sense anymore now that the `partisan` dependency offers a correct peer sampling service.

**Comment by cmeiklejohn** [comment]
Can you remove some of the debug logging?  That's going to cause a significant performance hit if the code is executed often.  (Unfortunately, even with a higher/lower log level, the debug code still gets dispatched.)

**Comment by lrascao** [comment]
maybe have a switch to turn it on/off then? it's really hard tracking down anything in this without some logging
(edit: typos)

**Comment by lrascao** [comment]
I've reworked it so now there's only debug when running tests

**Review by cmeiklejohn — APPROVED** [review]

**Pull request merged**
